import { Component, effect, inject, input, numberAttribute } from '@angular/core';
import { RouterLink } from '@angular/router';
import { FpCardComponent } from '../../shared/ui/card.component';
    import { FpIconComponent } from '../../shared/ui/icon.component';
import { ProjectDashboardStore } from './project-dashboard.store';

@Component({ selector: 'app-project-dashboard', standalone: true, imports: [RouterLink, FpCardComponent, FpIconComponent], template: `
<main class="dashboard"><header><a class="project-back-link" routerLink="/projects"><fp-icon name="arrow-left" /> Volver a proyectos</a><p class="eyebrow">Project pulse</p><h1>Dashboard</h1><p class="lede">La señal esencial del trabajo, en un solo vistazo.</p></header>
@if (store.loading()) { <p aria-live="polite">Cargando métricas…</p> } @if (store.error(); as error) { <p class="error" role="alert">{{ error }}</p> }
@if (store.dashboard(); as d) { <section class="hero-metrics" aria-label="Resumen"><fp-card><strong>{{ d.totalItems }}</strong><span>Ítems totales</span></fp-card><fp-card><strong>{{ d.completedItems }}</strong><span>Completados</span></fp-card><fp-card><strong>{{ d.backlogPendingCount }}</strong><span>En backlog</span></fp-card></section>
<section class="grid"><fp-card><h2>Flujo por columna</h2><ul>@for (column of d.columnCounts; track column.columnId) { <li><span>{{ column.name }}</span><b>{{ column.count }}</b></li>}</ul></fp-card><fp-card><h2>Prioridad</h2><ul>@for (priority of priorityEntries(d); track priority[0]) { <li><span>{{ priority[0] }}</span><b>{{ priority[1] }}</b></li>}</ul></fp-card><fp-card><h2>Sprint activo</h2>@if (d.activeSprint; as sprint) { <h3>{{ sprint.name }}</h3><p>{{ d.activeSprintCompletedItems }} de {{ d.activeSprintTotalItems }} completados</p> } @else { <p>No hay sprint activo.</p> }</fp-card><fp-card><h2>Carga por responsable</h2><ul>@for (person of d.workload; track person.assigneeId) { <li><span>{{ person.assigneeName }}</span><b>{{ person.count }}</b></li>} @empty { <li>Sin asignaciones</li> }</ul></fp-card></section>}
</main>`, styles: `:host{display:block}.dashboard{max-width:1100px;padding:clamp(1.25rem,4vw,3rem);color:var(--fp-text)}header{margin-bottom:2rem}h1,h2,h3,.eyebrow{font-family:var(--fp-font-display);margin:0}.eyebrow{color:var(--fp-accent);text-transform:uppercase;letter-spacing:.15em;font-size:.75rem;margin-top:1rem}.lede{color:var(--fp-text-muted)}.hero-metrics,.grid{display:grid;gap:1rem}.hero-metrics{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:repeat(2,1fr);margin-top:1rem}.hero-metrics fp-card{background:var(--fp-surface-strong);border-top:3px solid var(--fp-accent)}strong{display:block;font:2.5rem var(--fp-font-display);color:var(--fp-accent)}span{display:block;color:var(--fp-text-muted)}ul{list-style:none;padding:0;margin:1rem 0 0}li{display:flex;justify-content:space-between;padding:.7rem 0;border-bottom:1px solid var(--fp-border)}h2{font-size:1.15rem}a{color:var(--fp-accent)}.error{color:var(--fp-danger)}@media(max-width:600px){.hero-metrics,.grid{grid-template-columns:1fr}.hero-metrics{gap:.75rem}.dashboard{padding:1rem}.grid fp-card{min-width:0}}` })
export class ProjectDashboardComponent { readonly projectId=input.required<number,{transform:(v:string)=>number}>({transform:numberAttribute}); readonly store=inject(ProjectDashboardStore); constructor(){effect(()=>this.store.load(this.projectId()));} priorityEntries(d: {priorityDistribution: Record<string,number>}): [string,number][] { return Object.entries(d.priorityDistribution); } }
