package com.flowpilot.entity;
public enum ActivityEventType {
    PROJECT_CREATED, PROJECT_UPDATED, PROJECT_STATUS_CHANGED, WORK_ITEM_CREATED, WORK_ITEM_UPDATED,
    WORK_ITEM_STATUS_CHANGED, WORK_ITEM_MOVED, WORK_ITEM_DELETED, MEMBER_ADDED, MEMBER_REMOVED, MEMBER_ROLE_CHANGED,
    SPRINT_CREATED, SPRINT_UPDATED, SPRINT_STARTED, SPRINT_COMPLETED, COMMENT_CREATED, COMMENT_UPDATED,
    COMMENT_DELETED
}
